      version: '2'
      services:
        nginx:
          image: nginx
          container_name: nginx
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - "/etc/nginx/conf.d"
            - "/etc/nginx/vhost.d:/etc/nginx/vhost.d"
            - "/usr/share/nginx/html:/usr/share/nginx/html"
            - "./roles/nginx/volumes/proxy/certs:/etc/nginx/certs:ro"
            - "./apps/web/:/usr/share/nginx/html:ro"
            - "./apps/web/nginx-dev.conf:/etc/nginx/nginx.conf:ro"
          networks:
            - proxy-tier
        nginx-gen:
          image: jwilder/docker-gen
          container_name: nginx-gen
          volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./roles/nginx/volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
          volumes_from:
            - nginx
          entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        letsencrypt-nginx-proxy-companion:
          image: jrcs/letsencrypt-nginx-proxy-companion
          container_name: letsencrypt-nginx-proxy-companion
          volumes_from:
            - nginx
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./roles/nginx/volumes/proxy/certs:/etc/nginx/certs:rw"
          environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      networks:
        proxy-tier:
          external:
            name: nginx-proxy