---

- name: Deploy webapps
  docker_service:
    state: "{{ state }}"
    project_name: webapps
    definition:
      version: "2"
      services:
        develfactory-api:
          build: "{{ playbook_dir }}/apps/api/."
          ports:
            - "80"
            - "5000"
          volumes:
            - "{{ playbook_dir }}/apps/api/:/app"
          networks:
            - proxy-tier
          environment:
            VIRTUAL_HOST: "local.api.develfactory.net"
            VIRTUAL_PORT: "5000"
            VIRTUAL_NETWORK: "nginx-proxy"
        develfactory-web:
          build: "{{ playbook_dir }}/apps/web/."
          ports:
            - "80"
            - "5000"
          volumes:
            - "{{ playbook_dir }}/apps/web/:/usr/share/nginx/html"
            - "{{ playbook_dir }}/apps/web/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "{{ playbook_dir }}/apps/web/nginx-dev.conf:/etc/nginx/nginx.conf:ro"
          networks:
            - proxy-tier
          environment:
            VIRTUAL_HOST: "local.develfactory.net"
            VIRTUAL_PORT: "80"
            VIRTUAL_NETWORK: "nginx-proxy"
      networks:
        proxy-tier:
          external:
            name: nginx-proxy